name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  REGION: ${{ secrets.GCP_REGION }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Secrets Population
        run: |
          echo "Project ID length: ${#PROJECT_ID}"
          echo "Service Name length: ${#SERVICE_NAME}"
          echo "Region length: ${#REGION}"
          echo "WIP length: ${#WORKLOAD_IDENTITY_PROVIDER}"
          echo "Service Account length: ${#SERVICE_ACCOUNT}"
          
          # Check if any are empty
          [[ -z "$PROJECT_ID" ]] && echo "⚠️ PROJECT_ID is empty" || echo "✓ PROJECT_ID is set"
          [[ -z "$SERVICE_NAME" ]] && echo "⚠️ SERVICE_NAME is empty" || echo "✓ SERVICE_NAME is set"
          [[ -z "$REGION" ]] && echo "⚠️ REGION is empty" || echo "✓ REGION is set"
          [[ -z "$WORKLOAD_IDENTITY_PROVIDER" ]] && echo "⚠️ WIP is empty" || echo "✓ WIP is set"
          [[ -z "$SERVICE_ACCOUNT" ]] && echo "⚠️ SERVICE_ACCOUNT is empty" || echo "✓ SERVICE_ACCOUNT is set"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          echo "Starting deployment to Cloud Run"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
          echo "Deployment to Cloud Run completed"
